const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require('puppeteer-core');

const gemini = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
});

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("The match score between the candidate and the job role (0-100)"),

    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question to be asked in the interview"),
        answer: z.string().describe("How to answer this question, what points to cover"),
        intention: z.string().describe("The intention of interviewer behind this question")
    })).describe("Technical questions with their intention and how to answer them"),

    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question to be asked in the interview"),
        answer: z.string().describe("How to answer this question, what points to cover"),
        intention: z.string().describe("The intention of interviewer behind this question")
    })).describe("Behavioral questions with their intention and how to answer them"),

    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which candidate is lacking"),
        severity: z.enum(["low", "medium", "high"]).describe("Severity level of the skill gap")
    })).describe("Skill gaps the candidate has for the applied role with severity levels"),

    preparationPlan: z.array(z.object({
        day: z.number().describe("Day number in the preparation plan"),
        focus: z.string().describe("Main focus or topic for that day"),
        tasks: z.array(z.string()).describe("Specific tasks to complete on that day")
    })).describe("Day-by-day preparation plan for the interview"),

    title: z.string().describe("Job title which the interview report is generated"),

});
// Generating pdf from html with puppeteer
const htmlToPdfGenerate = async (htmlResume) => {
    const browser = await puppeteer.launch({
        executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
        headless: "new",
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    await page.setContent(htmlResume, {
        waitUntil: 'networkidle2',
    });

    const pdfBuffer = await page.pdf({
        format: "A4",
        margin: {
            top: "20mm",
            bottom: "20mm",
            left: "10mm",
            right: "10mm"
        }
    });
    await browser.close();
    return pdfBuffer

}

// for generating interview report
const generateInterviewReport = async ({ resume, jobDescription, selfDescription }) => {
    const prompt = `Generate an interview report based on the following information:
Job Description: ${jobDescription}
Resume: ${resume}
Self Description: ${selfDescription}
    `;

    try {
        const response = await gemini.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseJsonSchema: zodToJsonSchema(interviewReportSchema),  // ✅ Correct key
            }
        });

        const parsed = JSON.parse(response.text);  // ✅ Parse the JSON string
        return parsed;
    } catch (error) {
        console.error("Error invoking Gemini API:", error);
    }
};

// For Generating resume pdf 

const generateResumePdf = async ({ resume, jobDescription, selfDescription }) => {
    const resumePdfSchema = z.object({ resumeHtml: z.string().describe("The html content of the resume which can be provided to puppeteer library to generate pdf ") });
    const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `
    try {
        const response = await gemini.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseJsonSchema: zodToJsonSchema(resumePdfSchema),
            }
        });

        const parsed = JSON.parse(response.text);
        const pdfBuffer = await htmlToPdfGenerate(parsed.resumeHtml);
        return pdfBuffer;
    } catch (error) {
        console.error("Error on Generating Resume ", error);
        throw error;
    }
}

module.exports = { generateInterviewReport, generateResumePdf };